apiVersion: v1
kind: Pod
metadata:
  name: gpu-devicequery-test
  labels:
    app: gpu-smoke-test
spec:
  restartPolicy: Never
  containers:
    - name: devicequery
      image: ghcr.io/baillielab/cuda-sample:devicequery-cuda12.5.0-ubuntu22.04
      resources:
        limits:
          nvidia.com/gpu: 1
